### ISSUE TITLE
Default image while loading?

### ISSUE THREAD

**Issue by factormystic** [Q42/Q42.WinRT#10]
When using `q42controls:ImageExtensions.CacheUri` on an `Image`, it would be great if there was a way to specify a default/loading image while the extension is downloading the remote image.

For example, if the default `Source` binding could work normally (or be used by the extension) until complete, that would be excellent.

**Comment by michielpost** [comment]
Just did some testing and it already works as suggested. You can use the normal Source binding and it will show the image untill the source is set by the cached image.

**Comment by Akhilsa** [comment]
Hi Michiel,

Thanks  for the wonder full effort. You saved my day. I am developing a WP8.1 application(not in silver light) and used 'q42controls:ImageExtensions.CacheUri' instead of image source property.  I am wondering is there any chance that I can show a default image if the application is offline and the image was not downloaded before ? I tired setting the source property but no use. Please help. 
 Here is my XAML.

<Image Margin="8"
  VerticalAlignment="Top"
   Width="120"
   Height="120" Stretch="UniformToFill"  q42controls:ImageExtensions.CacheUri="{Binding Path=imageUrl}" />

Thanks in advance.

**Comment by michielpost** [comment]
@Akhilsa you can set the normal Source property and it will be used as default image while loading.
