### ISSUE TITLE
ToCacheKey() extension method returns not unique values

### ISSUE THREAD

**Issue by hva** [Q42/Q42.WinRT#17]
Could you please check ToCacheKey method?
I think following line is not correct:
`string hashedResult = uri.GetHashCode().ToString();`
Should be without GetHashCode().
Otherwise Regex.Replace does not make sense and results are not unique.

**Comment by michielpost** [comment]
I choose to has the uri to generate a cache key to solve two problems:
The cache key has a maximum length, because it is stored a file and there is a max path length and because not all characters in an uri are allowed in a file path.
Simply filtering those characters could also cause duplicate cache keys.

The hashing algorithm can cause duplicate's, but I think it's not very likely. Or did you see duplicate results?

**Comment by hva** [comment]
No I did not see any duplicates.
If you think the code is correct - it's fine for me.
Thank you for the quick answer.
